# Generated by Django 5.0.4 on 2024-04-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='guest',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=3),
        ),
    ]
